import sanityClient from "./sanityClient";

export async function fetchHomepage() {
  const query = `*[_type == "homepage"][0]{
    title,
    description,
    homePageImages[]{
      asset->{
        _id,
        url
      }
    },
    heroImgText,
    backgroundSvg{
      asset->{
        _id,
        url
      }
    },
    groupIconsImages[]{
      asset->{
        _id,
        url
      }
    },
    healthCareProvidersImages[]{
      asset->{
        _id,
        url
      }
    },
    pmbSolutionsTitle,
    pmbSolutionsDescription,
    pmbSolutionsImage{
      asset->{
        _id,
        url
      }
    },
    ourServicesTitle,
    ourServicesDescription,
    servicesSections[]{
      serviceTitle,
      serviceImage{
        asset->{
          _id,
          url
        }
      },
      serviceDescription
    },
    howOurPlatformWorks,
    howOurPlatformWorksDescription,
    howOurPlatformWorksImage{
      asset->{
        _id,
        url
      }
    },
    howPlatformWorksSections[]{
      serviceTitle,
      serviceImage{
        asset->{
          _id,
          url
        }
      },
      serviceDescription
    },
    learnMoreSection,
    learnMoreSectionDescription,
    learnMoreSectionImage{
      asset->{
        _id,
        url
      }
    },
    bookAppointmentTitle,
    bookAppointmentDescription,
    bookAppointmentBenefits[]{
      benefit,
      benefitIcon{
        asset->{
          _id,
          url
        }
      }
    },
    bookAppointmentImage{
      asset->{
        _id,
        url
      }
    },
    sideIcons[]{
      asset->{
        _id,
        url
      }
    }
  }`;

  const homepage = await sanityClient.fetch(query);
  console.log(homepage); // Add this line to inspect the fetched data
  return homepage;
}
